name: test

on:
  watch:
    types: [started]

jobs:
  handle-stars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Testing star
        run: |
          if [ "${{ github.event.action }}" == "started" ]; then
            echo "Repo starred by ${{ github.event.sender.login }}"
          elif [ "${{ github.event.action }}" == "deleted" ]; then
            echo "Repo unstarred by ${{ github.event.sender.login }}"
          fi
